export const tags = [
  { id: 'multiverse', label: 'Multiverse', tone: 'red' },
  { id: 'avengers', label: 'Avengers', tone: 'gold' },
  { id: 'street-level', label: 'Street Level', tone: 'steel' },
  { id: 'cosmic', label: 'Cosmic', tone: 'blue' },
  { id: 'legacy', label: 'Legacy', tone: 'gold' },
  { id: 'spoilers', label: 'Spoilers', tone: 'red' },
  { id: 'timeline', label: 'Timeline', tone: 'steel' },
  { id: 'rumor-watch', label: 'Rumor Watch', tone: 'red' },
]

export const movies = [
  {
    id: 'iron-man',
    title: 'Iron Man',
    releaseDate: '2008-05-02',
    phase: 'Phase 1',
    status: 'released',
    timeline: 1,
    description: 'Tony Stark builds the first Iron Man armor and starts the modern MCU chain reaction.',
    tags: ['legacy', 'avengers'],
    characters: ['iron-man', 'pepper-potts', 'nick-fury'],
    actors: ['robert-downey-jr', 'gwyneth-paltrow', 'samuel-l-jackson'],
    related: ['the-avengers', 'avengers-endgame'],
    featured: true,
  },
  {
    id: 'the-avengers',
    title: 'The Avengers',
    releaseDate: '2012-05-04',
    phase: 'Phase 1',
    status: 'released',
    timeline: 6,
    description: 'Earths first major hero team forms after Loki brings an alien invasion to New York.',
    tags: ['avengers', 'timeline'],
    characters: ['iron-man', 'captain-america', 'thor', 'black-widow', 'hulk'],
    actors: ['robert-downey-jr', 'chris-evans', 'chris-hemsworth', 'scarlett-johansson', 'mark-ruffalo'],
    related: ['iron-man', 'avengers-age-of-ultron', 'avengers-endgame'],
    featured: true,
  },
  {
    id: 'guardians-of-the-galaxy',
    title: 'Guardians of the Galaxy',
    releaseDate: '2014-08-01',
    phase: 'Phase 2',
    status: 'released',
    timeline: 10,
    description: 'A group of cosmic outsiders become an unlikely family while stopping Ronan.',
    tags: ['cosmic', 'legacy'],
    characters: ['star-lord', 'gamora'],
    actors: ['chris-pratt', 'zoe-saldana'],
    related: ['avengers-infinity-war'],
    featured: false,
  },
  {
    id: 'captain-america-civil-war',
    title: 'Captain America: Civil War',
    releaseDate: '2016-05-06',
    phase: 'Phase 3',
    status: 'released',
    timeline: 13,
    description: 'The Avengers split over accountability, loyalty, and the future of hero intervention.',
    tags: ['avengers', 'legacy'],
    characters: ['captain-america', 'iron-man', 'black-widow', 'spider-man'],
    actors: ['chris-evans', 'robert-downey-jr', 'scarlett-johansson', 'tom-holland'],
    related: ['the-avengers', 'black-panther', 'avengers-infinity-war'],
    featured: false,
  },
  {
    id: 'black-panther',
    title: 'Black Panther',
    releaseDate: '2018-02-16',
    phase: 'Phase 3',
    status: 'released',
    timeline: 15,
    description: 'TChalla returns to Wakanda and faces a challenge that reshapes the nation.',
    tags: ['legacy', 'timeline'],
    characters: ['black-panther', 'shuri'],
    actors: ['chadwick-boseman', 'letitia-wright'],
    related: ['captain-america-civil-war', 'avengers-infinity-war'],
    featured: true,
  },
  {
    id: 'avengers-infinity-war',
    title: 'Avengers: Infinity War',
    releaseDate: '2018-04-27',
    phase: 'Phase 3',
    status: 'released',
    timeline: 18,
    description: 'Heroes across Earth and space try to stop Thanos from completing the Infinity Stones.',
    tags: ['avengers', 'cosmic', 'spoilers'],
    characters: ['iron-man', 'captain-america', 'thor', 'spider-man', 'star-lord'],
    actors: ['robert-downey-jr', 'chris-evans', 'chris-hemsworth', 'tom-holland', 'chris-pratt'],
    related: ['avengers-endgame', 'guardians-of-the-galaxy'],
    featured: true,
  },
  {
    id: 'avengers-endgame',
    title: 'Avengers: Endgame',
    releaseDate: '2019-04-26',
    phase: 'Phase 3',
    status: 'released',
    timeline: 20,
    description: 'The surviving Avengers attempt a final time-heist to undo Thanos victory.',
    tags: ['avengers', 'timeline', 'legacy'],
    characters: ['iron-man', 'captain-america', 'thor', 'black-widow', 'hulk'],
    actors: ['robert-downey-jr', 'chris-evans', 'chris-hemsworth', 'scarlett-johansson', 'mark-ruffalo'],
    related: ['avengers-infinity-war', 'spider-man-no-way-home'],
    featured: true,
  },
  {
    id: 'spider-man-no-way-home',
    title: 'Spider-Man: No Way Home',
    releaseDate: '2021-12-17',
    phase: 'Phase 4',
    status: 'released',
    timeline: 28,
    description: 'Peter Parker asks Doctor Strange for help and opens a multiversal crisis.',
    tags: ['multiverse', 'street-level', 'spoilers'],
    characters: ['spider-man', 'doctor-strange'],
    actors: ['tom-holland', 'benedict-cumberbatch'],
    related: ['doctor-strange-mom', 'avengers-endgame'],
    featured: true,
  },
  {
    id: 'doctor-strange-mom',
    title: 'Doctor Strange in the Multiverse of Madness',
    releaseDate: '2022-05-06',
    phase: 'Phase 4',
    status: 'released',
    timeline: 30,
    description: 'Doctor Strange confronts multiversal consequences and a corrupted Scarlet Witch.',
    tags: ['multiverse', 'spoilers'],
    characters: ['doctor-strange', 'scarlet-witch'],
    actors: ['benedict-cumberbatch', 'elizabeth-olsen'],
    related: ['spider-man-no-way-home'],
    featured: false,
  },
  {
    id: 'avengers-doomsday',
    title: 'Avengers: Doomsday',
    releaseDate: '2026-12-18',
    phase: 'Phase 6',
    status: 'upcoming',
    timeline: 42,
    description: 'A major Avengers event positioned as the next large crossover chapter.',
    tags: ['avengers', 'rumor-watch'],
    characters: ['doctor-strange', 'spider-man'],
    actors: ['benedict-cumberbatch', 'tom-holland'],
    related: ['avengers-endgame'],
    featured: true,
  },
]

export const characters = [
  { id: 'iron-man', name: 'Iron Man', realName: 'Tony Stark', actorIds: ['robert-downey-jr'], traits: ['Inventor', 'Avenger', 'Sacrifice arc'], description: 'A genius engineer whose armor and choices define the first MCU saga.', tags: ['avengers', 'legacy'] },
  { id: 'captain-america', name: 'Captain America', realName: 'Steve Rogers', actorIds: ['chris-evans'], traits: ['Leader', 'Super soldier', 'Man out of time'], description: 'The moral center of the early Avengers era.', tags: ['avengers', 'legacy'] },
  { id: 'thor', name: 'Thor', realName: 'Thor Odinson', actorIds: ['chris-hemsworth'], traits: ['Asgardian', 'God of Thunder', 'Cosmic link'], description: 'A mythic hero connecting Earth to the larger cosmic MCU.', tags: ['cosmic', 'avengers'] },
  { id: 'black-widow', name: 'Black Widow', realName: 'Natasha Romanoff', actorIds: ['scarlett-johansson'], traits: ['Spy', 'Avenger', 'Red Room'], description: 'A grounded strategist and founding Avenger.', tags: ['avengers', 'legacy'] },
  { id: 'hulk', name: 'Hulk', realName: 'Bruce Banner', actorIds: ['mark-ruffalo'], traits: ['Gamma', 'Scientist', 'Dual identity'], description: 'A brilliant scientist living with uncontrollable strength.', tags: ['avengers'] },
  { id: 'spider-man', name: 'Spider-Man', realName: 'Peter Parker', actorIds: ['tom-holland'], traits: ['Street-level', 'Young hero', 'Multiverse survivor'], description: 'A neighborhood hero pulled into Avengers-scale conflicts.', tags: ['street-level', 'multiverse'] },
  { id: 'doctor-strange', name: 'Doctor Strange', realName: 'Stephen Strange', actorIds: ['benedict-cumberbatch'], traits: ['Sorcerer', 'Mystic arts', 'Multiverse'], description: 'A former surgeon who becomes a central guardian of reality.', tags: ['multiverse'] },
  { id: 'black-panther', name: 'Black Panther', realName: 'TChalla', actorIds: ['chadwick-boseman'], traits: ['King', 'Wakanda', 'Protector'], description: 'The Wakandan king whose legacy reshapes the wider MCU.', tags: ['legacy'] },
  { id: 'shuri', name: 'Shuri', realName: 'Shuri', actorIds: ['letitia-wright'], traits: ['Inventor', 'Wakanda', 'Royal family'], description: 'A brilliant technologist at the heart of Wakandas future.', tags: ['legacy'] },
  { id: 'star-lord', name: 'Star-Lord', realName: 'Peter Quill', actorIds: ['chris-pratt'], traits: ['Guardian', 'Cosmic', 'Found family'], description: 'A space outlaw whose messy choices ripple into cosmic events.', tags: ['cosmic'] },
  { id: 'gamora', name: 'Gamora', realName: 'Gamora', actorIds: ['zoe-saldana'], traits: ['Assassin', 'Guardian', 'Thanos link'], description: 'A survivor of Thanos who becomes key to the Guardians story.', tags: ['cosmic'] },
  { id: 'scarlet-witch', name: 'Scarlet Witch', realName: 'Wanda Maximoff', actorIds: ['elizabeth-olsen'], traits: ['Chaos magic', 'Grief arc', 'Multiverse threat'], description: 'A powerful magic user whose loss changes the shape of Phase 4.', tags: ['multiverse', 'spoilers'] },
  { id: 'pepper-potts', name: 'Pepper Potts', realName: 'Virginia Potts', actorIds: ['gwyneth-paltrow'], traits: ['CEO', 'Rescue armor', 'Stark link'], description: 'Tony Starks closest partner and the anchor of his personal life.', tags: ['legacy'] },
  { id: 'nick-fury', name: 'Nick Fury', realName: 'Nick Fury', actorIds: ['samuel-l-jackson'], traits: ['Strategist', 'SHIELD', 'Recruiter'], description: 'The connective thread behind the Avengers Initiative.', tags: ['avengers'] },
]

export const actors = [
  { id: 'robert-downey-jr', name: 'Robert Downey Jr.', roles: ['iron-man'], bio: 'The face of the first MCU era through Tony Starks rise, mistakes, and sacrifice.', trivia: ['First lead hero of the MCU', 'Anchors the Infinity Saga'] },
  { id: 'chris-evans', name: 'Chris Evans', roles: ['captain-america'], bio: 'Played Steve Rogers across the core Avengers era.', trivia: ['Central to the Civil War conflict'] },
  { id: 'chris-hemsworth', name: 'Chris Hemsworth', roles: ['thor'], bio: 'Brings Thor from mythic prince to cosmic survivor.', trivia: ['One of the longest-running MCU leads'] },
  { id: 'scarlett-johansson', name: 'Scarlett Johansson', roles: ['black-widow'], bio: 'Portrayed Natasha Romanoff from spy thriller roots to Avengers legacy.', trivia: ['Founding Avenger onscreen'] },
  { id: 'mark-ruffalo', name: 'Mark Ruffalo', roles: ['hulk'], bio: 'Represents Bruce Banner and Hulk through the team-up films.', trivia: ['Debuted in The Avengers'] },
  { id: 'tom-holland', name: 'Tom Holland', roles: ['spider-man'], bio: 'Plays the MCU version of Peter Parker across street-level and multiverse stories.', trivia: ['Introduced during Civil War'] },
  { id: 'benedict-cumberbatch', name: 'Benedict Cumberbatch', roles: ['doctor-strange'], bio: 'Connects the MCU to the mystic arts and multiverse rules.', trivia: ['Key Phase 4 multiverse figure'] },
  { id: 'chadwick-boseman', name: 'Chadwick Boseman', roles: ['black-panther'], bio: 'Defined TChalla with dignity, weight, and cultural force.', trivia: ['Debuted in Civil War'] },
  { id: 'letitia-wright', name: 'Letitia Wright', roles: ['shuri'], bio: 'Represents Shuris technical genius and Wakandan future.', trivia: ['Known for Wakandan tech scenes'] },
  { id: 'chris-pratt', name: 'Chris Pratt', roles: ['star-lord'], bio: 'Leads the Guardians ensemble as Peter Quill.', trivia: ['Connects comedy and cosmic stakes'] },
  { id: 'zoe-saldana', name: 'Zoe Saldana', roles: ['gamora'], bio: 'Portrays Gamora across the Guardians and Infinity Saga.', trivia: ['Key character in the Thanos story'] },
  { id: 'elizabeth-olsen', name: 'Elizabeth Olsen', roles: ['scarlet-witch'], bio: 'Carries Wanda Maximoffs path from Avenger to multiversal threat.', trivia: ['Central to Phase 4 theories'] },
  { id: 'gwyneth-paltrow', name: 'Gwyneth Paltrow', roles: ['pepper-potts'], bio: 'Appears as Pepper Potts across Tony Starks full arc.', trivia: ['Eventually suits up as Rescue'] },
  { id: 'samuel-l-jackson', name: 'Samuel L. Jackson', roles: ['nick-fury'], bio: 'Plays Nick Fury, the planner behind many early MCU connections.', trivia: ['Post-credit scene icon'] },
]

export const posts = [
  { id: 'p1', type: 'discussion', title: 'Endgames time-heist still feels like the cleanest finale structure', body: 'The movie lets every era breathe without turning the timeline into homework.', movieId: 'avengers-endgame', characterId: 'iron-man', actorId: 'robert-downey-jr', tags: ['timeline', 'avengers'], spoiler: 'high', upvotes: 126, comments: 18, featured: true, activeAt: '2h ago', author: 'arc-reactor' },
  { id: 'p2', type: 'theory', title: 'No Way Home quietly resets Peter into true street-level mode', body: 'The ending removes almost every shortcut and makes the next chapter smaller in the best way.', movieId: 'spider-man-no-way-home', characterId: 'spider-man', actorId: 'tom-holland', tags: ['street-level', 'multiverse'], spoiler: 'medium', upvotes: 98, comments: 27, featured: true, activeAt: '4h ago', author: 'webbed-notes' },
  { id: 'p3', type: 'discussion', title: 'Civil War is secretly the strongest character index page', body: 'It introduces, splits, and stress-tests almost every major relationship at once.', movieId: 'captain-america-civil-war', characterId: 'captain-america', actorId: 'chris-evans', tags: ['avengers', 'legacy'], spoiler: 'medium', upvotes: 72, comments: 12, featured: false, activeAt: '7h ago', author: 'shield-file' },
]

export const leaks = [
  { id: 'l1', title: 'Doomsday may center on multiverse team fragments', description: 'Early chatter suggests smaller teams moving through separate branches before converging.', movieId: 'avengers-doomsday', tags: ['rumor-watch', 'multiverse'], credibility: 'Medium', spoiler: 'high', status: 'unverified' },
  { id: 'l2', title: 'Spider-Man sequel rumored to lean street-level first', description: 'The current signal points to grounded New York stakes before larger crossover setup.', movieId: 'spider-man-no-way-home', tags: ['street-level', 'rumor-watch'], credibility: 'Low', spoiler: 'medium', status: 'speculative' },
]

export const facts = [
  { id: 'f1', text: 'Iron Man is the seed point for the platform timeline.', entityType: 'movie', entityId: 'iron-man' },
  { id: 'f2', text: 'Endgame closes the first long-form Avengers arc.', entityType: 'movie', entityId: 'avengers-endgame' },
  { id: 'f3', text: 'Tony Stark is linked to the most featured Phase 1 to 3 pages.', entityType: 'character', entityId: 'iron-man' },
  { id: 'f4', text: 'Robert Downey Jr. anchors the most manually featured movies in the seed set.', entityType: 'actor', entityId: 'robert-downey-jr' },
  { id: 'f5', text: 'No Way Home is tagged as both street-level and multiverse.', entityType: 'movie', entityId: 'spider-man-no-way-home' },
]

export const users = [
  { id: 'u1', username: 'arc-reactor', posts: 9, saved: ['avengers-endgame', 'p1'], status: 'active' },
  { id: 'u2', username: 'webbed-notes', posts: 5, saved: ['spider-man-no-way-home', 'p2'], status: 'active' },
  { id: 'u3', username: 'variant-watch', posts: 3, saved: ['l1'], status: 'restricted' },
]

export const reports = [
  { id: 'r1', target: 'Comment on Doomsday leak', reason: 'Unmarked spoilers', status: 'open' },
  { id: 'r2', target: 'Theory thread reply', reason: 'Duplicate rumor source', status: 'open' },
]
