export const initialData = {
  movies: [],
  characters: [],
  actors: [],
  tags: [],
  posts: [],
  leaks: [],
  facts: [],
  users: [],
  reports: [],
  settings: {
    siteName: 'Nexus',
    tagline: 'MCU movies, characters, actors, discussions, leaks, and facts.',
    postingEnabled: true,
    spoilerRules: 'Mark spoilers clearly on discussions, theories, and leaks.',
    seoTitle: 'Nexus',
    seoDescription: 'A clean MCU content platform managed from an admin panel.',
  },
}

export const emptyDrafts = {
  movies: {
    title: '',
    releaseDate: '',
    phase: '',
    status: 'released',
    description: '',
    timeline: '',
    featured: false,
    tags: [],
    characters: [],
    actors: [],
    related: [],
    seoTitle: '',
    seoDescription: '',
  },
  characters: {
    name: '',
    realName: '',
    description: '',
    traits: [],
    tags: [],
    actorIds: [],
    movieIds: [],
  },
  actors: {
    name: '',
    bio: '',
    trivia: [],
    roles: [],
    movieIds: [],
  },
  tags: {
    label: '',
    tone: 'red',
    description: '',
  },
  posts: {
    type: 'discussion',
    title: '',
    body: '',
    movieId: '',
    characterId: '',
    actorId: '',
    tags: [],
    spoiler: 'none',
    upvotes: 0,
    comments: 0,
    featured: false,
    pinned: false,
    author: '',
  },
  leaks: {
    title: '',
    description: '',
    movieId: '',
    tags: [],
    credibility: 'Low',
    spoiler: 'none',
    status: 'unverified',
    approved: false,
  },
  facts: {
    text: '',
    entityType: 'movie',
    entityId: '',
    priority: 1,
  },
  users: {
    username: '',
    status: 'active',
    notes: '',
  },
  reports: {
    target: '',
    reason: '',
    status: 'open',
  },
}
